[[website]]
name = "demo.resare.com"
replicas = 1
args = ["-c", "/config/config.toml"]
config = { "/config/config.toml" = "oidc-client-demo.toml" }
random-secret = "session-key"
external-secret = "/secret"
