# Application configuration for oidc-client-demo

[app]
secret_key_path = "/random-secrets/session-key"
base_url = "https://demo.resare.com"

[oidc]
issuer = "https://login.microsoftonline.com/1b5955bf-2426-4ced-8412-9fe81bb8bca4/v2.0"
client_id = "82121173-5d45-4932-9067-8872b8735206"
scopes = ["openid", "profile", "email", "offline_access", "https://graph.microsoft.com/User.Read"]
client_secret_path = "/secret/client_id"

[otel]
endpoint = "http://tempo.tempo.svc:4318/v1/traces"
service_name = "oidc-client-demo"
